"project_id" : "512896"
"base_path" : "."
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
 {
  "source" : "/src/translations/locales/en-GB.json",
  "translation" : "/src/translations/locales/%locale%.json"
 }
]