apiVersion: v1
kind: Service
metadata:
  name: rb-backend-cluster-ip-service
  labels:
    service: rb-backend
spec:
  type: ClusterIP
  selector:
    component: rb-backend
  ports:
    - port: 3201
      targetPort: 3201
