apiVersion: apps/v1
kind: Deployment
metadata:
  name: rb-pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rb-pgadmin
  template:
    metadata:
      labels:
        component: rb-pgadmin
    spec:
      volumes:
        - name: rb-pgadmin-storage
          persistentVolumeClaim:
            claimName: rb-pgadmin-persistent-volume-claim
      containers:
        - name: rb-pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: rb-pgadmin-storage
              mountPath: /var/lib/pgadmin
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: retrospected-secrets
                  key: PGADMIN_USER
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retrospected-secrets
                  key: PGADMIN_PASSWORD
