apiVersion: v1
kind: Service
metadata:
  name: rb-postgres-cluster-ip-service
  labels:
    service: rb-postgres
spec:
  type: ClusterIP
  selector:
    component: rb-postgres
  ports:
    - port: 5432
      targetPort: 5432
