apiVersion: v1
kind: Service
metadata:
  name: rb-redis-cluster-ip-service
  labels:
    service: rb-redis
spec:
  type: ClusterIP
  selector:
    component: rb-redis
  ports:
    - port: 6379
      targetPort: 6379
