version: '3'
services:
  fe:
    image: retrospected/frontend:local
    ports:
      - '3000:80'
    restart: unless-stopped
    environment:
      BACKEND_HOST: host.docker.internal
      BACKEND_PORT: 8081
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
