name: CI

on:
  push:
    branches: [v4]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read VERSION
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Echo VERSION
        run: echo ${{ steps.package.outputs.content }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: retro-board-server/Dockerfile
          context: .
          tags: antoinejaussoin/retro-board-backend:v4
          platforms: linux/amd64,linux/arm64
          push: true

      - name: Build and push Frontend
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: retro-board-app/Dockerfile
          context: .
          tags: antoinejaussoin/retro-board-frontend:v4
          platforms: linux/amd64,linux/arm64
          push: true

      - name: Build and push Maintenance
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: retro-board-maintenance/Dockerfile
          context: retro-board-maintenance
          tags: antoinejaussoin/retro-board-maintenance:v4
          platforms: linux/amd64,linux/arm64
          push: true
